name: Build Expo App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Get build number from commit count
        id: build_number
        run: |
          echo "BUILD_NUM=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Build with EAS and dynamic message
        run: eas build --platform android --profile production --non-interactive --message "Build #${{ env.BUILD_NUM }}" --wait --output=./app-release.aab
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUILD_NUM }}
          name: Release v${{ env.BUILD_NUM }}
          body: |
            ✅ Nouveau build Expo Android
            🔢 Numéro : Build #${{ env.BUILD_NUM }}
            🧱 Généré via GitHub Actions CI/CD
          files: ./app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
